### ISSUE TITLE
ImportError: cannot import name '_app_ctx_err_msg' from 'flask.globals'

### ISSUE THREAD

**Issue by skate15e** [simon7426/InfluxDB-Flask#2]
Below error raised when trying to run Flask app.  It appears the error has been removed from globals.py.

Error: While importing 'app', an ImportError was raised:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/flask/cli.py", line 218, in locate_app
    __import__(module_name)
  File "/Users/raygunter/docker/apache/app.py", line 13, in <module>
    from influxdb_flask import InfluxDB
  File "/opt/homebrew/lib/python3.10/site-packages/influxdb_flask/__init__.py", line 3, in <module>
    from .influxdb_flask import InfluxDB
  File "/opt/homebrew/lib/python3.10/site-packages/influxdb_flask/influxdb_flask.py", line 3, in <module>
    from flask.globals import _app_ctx_err_msg
ImportError: cannot import name '_app_ctx_err_msg' from 'flask.globals' (/opt/homebrew/lib/python3.10/site-packages/flask/globals.py)

**Comment by skate15e** [comment]
Update:  It appears this occurs when using Flask 2.2.0 or higher.  After rolling back to Flask 2.1.3, the error goes away.
